### ISSUE TITLE
Highlighting a path is broken

### ISSUE THREAD

**Issue by liberostelios** [p-ortmann/dyntapy#2]
When trying to `calculating_shortest_path` example from the examples, I cannot see the shortest path highlighted:

<img width="887" alt="Screenshot 2022-07-27 at 13 52 59" src="https://user-images.githubusercontent.com/1896327/181241133-7075430c-13ce-4f2a-99a1-985772bb89e1.png">

There seems to be some colouring that breaks. Here is a zoomed in screenshot:

<img width="884" alt="Screenshot 2022-07-27 at 13 58 24" src="https://user-images.githubusercontent.com/1896327/181241368-142d1c99-d03a-4531-8ad5-084f04b5c3d1.png">

**Comment by p-ortmann** [comment]
Thank you for reporting this! I've already run into it but was not aware that it was also affecting the environment in Binder.
The problem is that the order of the points in the polygon creation from the geometries gets mingled for some environments. This was not an issue when v0.2.2 was rolled out, but since the dependencies are not fixed it has become an issue recently ..
I've just updated the tutorials to an environment with fixed dependencies that does not have the issue. 

For upcoming versions the polygon creation no longer relies on the order of the points that are returned. See https://github.com/p-ortmann/dyntapy/commit/a7956814f992c15f83c909cee428a14295abfc5f#diff-9544bc87e8cb5609732706630974b6f814b861d43e16c5520b3fb162f3e97e3eR960
